
import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface LegalDocsProps {
  onBack: () => void;
  docType: 'privacy' | 'terms';
}

export const LegalDocs: React.FC<LegalDocsProps> = ({ onBack, docType }) => {
  return (
    <div className="fixed inset-0 z-[100] bg-slate-900 text-slate-300 overflow-y-auto animate-in slide-in-from-right duration-300">
        <div className="max-w-2xl mx-auto p-6">
            {/* Header */}
            <div className="sticky top-0 bg-slate-900/95 backdrop-blur-sm py-4 mb-6 border-b border-slate-800 flex items-center gap-3 z-10">
                <button onClick={onBack} className="p-2 -ml-2 text-slate-400 hover:text-white rounded-full hover:bg-slate-800 transition-colors">
                    <ArrowLeft className="w-6 h-6" />
                </button>
                <h1 className="text-xl font-bold text-white">
                    {docType === 'privacy' ? 'Privacy Policy' : 'Terms of Service'}
                </h1>
            </div>

            <div className="prose prose-invert prose-slate max-w-none pb-20">
                {docType === 'privacy' ? (
                    <>
                        <h3>Privacy Policy</h3>
                        <p className="text-sm text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>
                        
                        <h4>1. Introduction</h4>
                        <p>Welcome to RizzMaster AI. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our application.</p>

                        <h4>2. Data We Collect</h4>
                        <p>We collect minimal data to provide our services:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>Uploaded Images:</strong> Images (screenshots) are processed in temporary memory by our AI provider (Google Gemini) and are NOT permanently stored on our servers. They are discarded immediately after analysis.</li>
                            <li><strong>Local Preferences:</strong> We use LocalStorage on your device to save your language settings, MBTI profile, and saved partners for your convenience. This data stays on your device.</li>
                            <li><strong>Usage Data:</strong> We may use Google Analytics to collect anonymous usage statistics to improve the app.</li>
                        </ul>

                        <h4>3. Advertising</h4>
                        <p>We use Google AdSense to display advertisements. Google may use cookies (DART cookies) to serve ads based on your visit to this site and other sites on the Internet. You may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>

                        <h4>4. Third-Party Links</h4>
                        <p>Our application may include links to third-party websites or services (e.g., payment providers). We do not control these third-party websites and are not responsible for their privacy statements.</p>
                        
                        <h4>5. Contact Us</h4>
                        <p>If you have any questions about this Privacy Policy, please contact us at support@rizzmaster.ai.</p>
                    </>
                ) : (
                    <>
                        <h3>Terms of Service</h3>
                        <p className="text-sm text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>
                        
                        <h4>1. Agreement to Terms</h4>
                        <p>By accessing RizzMaster AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, you are prohibited from using this application.</p>

                        <h4>2. Disclaimer</h4>
                        <p>The content and advice provided by RizzMaster AI are generated by Artificial Intelligence. They are for entertainment and informational purposes only. We make no guarantees regarding the effectiveness of the advice for dating or relationships. Use your own judgment.</p>

                        <h4>3. User Conduct</h4>
                        <p>You agree not to use the application for any unlawful purpose or to harass, abuse, or harm others.</p>

                        <h4>4. Intellectual Property</h4>
                        <p>The code, design, and branding of RizzMaster AI are owned by the developers. You may not copy or reproduce them without permission.</p>

                        <h4>5. Limitations</h4>
                        <p>In no event shall RizzMaster AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the materials on RizzMaster AI's website.</p>
                    </>
                )}
            </div>
        </div>
    </div>
  );
};